import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider, ThemeConfig } from "antd";
import { StyledComponentsRegistry } from "@/lib/registry";
import MainLayout from "../_layout";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const config: ThemeConfig = {
  token: {
    colorPrimary: "#cf0a0a",
    colorTextBase: "#fff",
    colorBgBase: "#000",
  },
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();
  const direction = locale === "ar" ? "rtl" : "ltr";
  console.log("local =>", locale);
  return (
    <NextIntlClientProvider messages={messages}>
      <html lang={locale}>
        <body
          className={`${geistSans.variable} ${geistMono.variable}`}
          suppressHydrationWarning={true}
        >
          <StyledComponentsRegistry>
            <AntdRegistry>
              <ConfigProvider theme={config} direction={direction}>
                <MainLayout>{children}</MainLayout>
              </ConfigProvider>
            </AntdRegistry>
          </StyledComponentsRegistry>
        </body>
      </html>
    </NextIntlClientProvider>
  );
}
